[package]
name = "matrix-url-previewer-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
color-eyre = "0.6.5"
deadpool-sqlite = { version = "*", features = ["tracing"] }
encoding_rs = "0.8.41"
eyre = "0.6.14"
indexmap = "2.14.2"
matrix-sdk = { version = "0.19.0", features = ["eyre", "socks"] }
matrixbot-ezlogin = "0.4.1"
mime = "0.3.17"
moka = { version = "0.12.16", features = ["future"] }
nom = "8.0.0"
regex = "1.13.1"
reqwest = { version = "0.13.5", features = ["brotli", "charset", "deflate", "gzip", "http2", "socks", "stream", "system-proxy", "zstd"] }
scraper = "0.27.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_with = "3.23.0"
stacksafe = "1.0.3"
tokio = { version = "1.53.1", features = ["full"] }
toml = "1.1.6"
tracing = "0.1.44"
tracing-error = "0.2.1"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
url = "2.5.8"

[features]
bundled-sqlite = ["matrix-sdk/bundled-sqlite", "matrixbot-ezlogin/bundled-sqlite"]
